### ISSUE TITLE
Problems of multi GPU inference

### ISSUE THREAD

**Issue by zjutkarma** [JoshuaChou2018/SkinGPT-4#5]
Hi, thanks for sharing the public code.
I'm running this demo.py file, but I encounter a calculation resource problem.
My 3090 machine contains **8 GPU(24GB each)**, but I can't run the demo.py file in one specific GPU because of the memory limit.

The error message is:
Traceback (most recent call last):
  File "/home/code/SkinGPT-4-main/demo.py", line 75, in <module>
    model = model_cls.from_config(model_config).to('cuda:0')
  File "/home/anaconda_local/envs/skingpt4_llama2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/anaconda_local/envs/skingpt4_llama2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/anaconda_local/envs/skingpt4_llama2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/anaconda_local/envs/skingpt4_llama2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/anaconda_local/envs/skingpt4_llama2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/anaconda_local/envs/skingpt4_llama2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: **CUDA out of memory**. Tried to allocate 136.00 MiB (GPU 0; 23.69 GiB total capacity; 23.13 GiB already allocated; 134.06 MiB free; 23.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

To address this problem, I search for some solutions. I've tried to modify the llama **from_pretained** function in skingpt4.py, to set the parameter  device_map to "auto" and set the os environment variable 'CUDA_VISIBLE_DEVICES' to 0,1, which means the llama model can allocate automately in gpu 0 and 1, but the error still exists.

And there's no parameter in **from_config** function in demo.py to control the GPU allocation, is there any opportunity to allocate the model manually? I'm afraid the process is complicated.

I'm confused about the problem and wonder how I can solve it. I recognize that in your paper you use 2 V100(32GB) to train the model, and in the demo.py **I guess the inference process can be done in one V100(32GB), is that right?** **But my single GPU memory is a little bit smaller and I wonder how I can inference by using two 24GB GPUs on my machine.**

Looking forward to your reply! :)

**Comment by JoshuaChou2018** [comment]
Hi, we will load the model weights to the CPU and then to one GPU by default. To meet your requirement, referring to https://huggingface.co/docs/accelerate/usage_guides/big_modeling might be helpful.

**Comment by zjutkarma** [comment]
yeahhhh I put all models on the gpu(set the function cuda()) and it works. The data needs to convert into half() on the gpu.
